### ISSUE TITLE
数据集尺寸问题

### ISSUE THREAD

**Issue by terhh996** [EnzeZhu2001/UNetMamba#4]
我们的数据集是256乘以256的tif格式的图片 并且只有一个目标区域 即二分法
请问这个模型可以使用我们的数据集嘛 如果可以使用 请问需要修改的部分是哪些？
期待您的回复

**Comment by EnzeZhu2001** [comment]
> 我们的数据集是256乘以256的tif格式的图片 并且只有一个目标区域 即二分法 请问这个模型可以使用我们的数据集嘛 如果可以使用 请问需要修改的部分是哪些？ 期待您的回复

可以的。首先，您需要在_unetmamba_model/datasets_中增加自己的xxx_dataset.py文件以设置类别和尺寸，具体代码结构可以参照vaihingen_dataset.py。然后，在_config_中参照vaihingen/unetmamba.py的结构编写自己的配置代码（主要是调用您的xxx_dataset，替换数据集加载的代码段，设置image_size = 256，模型无需调整）。
Tips：您数据集中的mask，即ground truth最好转换成.png格式。
