### ISSUE TITLE
About Mamba2

### ISSUE THREAD

**Issue by 5632515** [EnzeZhu2001/UNetMamba#5]
请问大佬有打算基于 mamba2 进行预训练吗 貌似性能比 原版 mamba 更高

**Comment by EnzeZhu2001** [comment]
> 请问大佬有打算基于 mamba2 进行预训练吗 貌似性能比 原版 mamba 更高

不敢当不敢当😄
确实，根据mamba2原文，在推理速度上有了显著的提升。您说的是个不错的思路，值得尝试。
（不过目前的研究重心已经不在RS SS了，我们应该不会去实操
