### ISSUE TITLE
NameError: name 'selective_scan_cuda_core' is not defined

### ISSUE THREAD

**Issue by renfangjun** [EnzeZhu2001/UNetMamba#6]
NameError: name 'selective_scan_cuda_core' is not defined,but I am installed causal-conv1d 1.2.0.post2,still can't run

**Comment by renfangjun** [comment]
NameError: name 'selective_scan_cuda_core' is not defined,but I am installed causal-conv1d 1.2.0.post2、mamba-ssm               1.1.1,still can't run

**Comment by renfangjun** [comment]
thinks for author,because of I don't have pip install the 'selective-scan @ file:///media/repository/renfangjun/Code/UNetMamba-main/unetmamba_model/kernels/selective_scan'.

**Comment by EnzeZhu2001** [comment]
> thinks for author,because of I don't have pip install the 'selective-scan @ file:///media/repository/renfangjun/Code/UNetMamba-main/unetmamba_model/kernels/selective_scan'.↳

Happy to hear that you have solved this error. If you have any other issues in the future, feel free to ask us.
